### ISSUE TITLE
gas & water meter not appearing in HA energy dashboard

### ISSUE THREAD

**Issue by Xander-V** [myTselection/pixometer#11]
According to HA the integration fails to show in the dashboard because of incorrect statistics and tells me to notify the developer of the following about statistics: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Energy seems to work fine and can be selected as a source in the dashboard, but both the gas and water meter cannot. 

When comparing the three meters, all necessary information seems to be present, the only difference I see is energy is state_class "total" vs gas & water have state_class "total_increasing"? Could that be the issue or is there something else?

![image](https://github.com/myTselection/pixometer/assets/97856913/3465376b-d371-4a9c-9431-1e1c5243d855)

**Comment by myTselection** [comment]
Strange, I have my pixometer watermeter sensor connected to the energy dashboard of Home Assistant.
Maybe some sensor statistics might need to be cleaned within HA, as I only recently fixed the state_class.
Within Menu Developer > Statistics, could you check if there are not warnings with a 'Fix this' option that may resolve this issue for you?

**Comment by Xander-V** [comment]
You are so right! I simply repaired the pixometer items and could add them to energy dashboard after that! Thanks
